### ISSUE TITLE
Question about ports is incorrect

### ISSUE THREAD

**Issue by brianharwell** [dgkanatsios/CKAD-exercises#100]
I am referring to [Create a pod with image nginx called nginx and allow traffic on port 80](https://github.com/dgkanatsios/CKAD-exercises/blob/master/a.core_concepts.md#create-a-pod-with-image-nginx-called-nginx-and-allow-traffic-on-port-80)

The solution is `kubectl run nginx --image=nginx --restart=Never --port=80` but this isn't correct.

This command results in the following yaml

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
spec:
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
```

`containerPort` does not permit or deny traffic, it simply exposes the port. Exposing ports is a good practice because it serves as documentation but if port 80 was not exposed traffic to port 80 would still work.

What I did to make this question correct and challenging was to reword the question to be

> Create a pod with image nginx called nginx and deny all traffic except port 80

From here I created the pod as per the example but then had to create a [Network Policy](https://kubernetes.io/docs/concepts/services-networking/network-policies/) to block all other ports
