### ISSUE TITLE
Network Policies quizlet doesn't prohibit access to the protected service

### ISSUE THREAD

**Issue by jeblackburn** [dgkanatsios/CKAD-exercises#123]
Hi,

I'll look at this once I'm done w/ my CKAD exam. This set of commands doesn't protect the target service/pods
`kubectl run nginx --image=nginx --replicas=2 --port=80 --expose`

```
kind: NetworkPolicy
apiVersion: networking.k8s.io/v1
metadata:
  name: access-nginx # pick a name
spec:
  podSelector:
    matchLabels:
      run: nginx # selector for the pods
  ingress: # allow ingress traffic
  - from:
    - podSelector: # from pods
        matchLabels: # with this label
          access: granted
```

`kubectl create -f <file>`

`kubectl run busybox --image=busybox --rm -it --restart=Never -- wget -O- http://nginx:80 --timeout 2 `

The call goes through to the Pod. The network policy is ignored. Still looking at it, maybe a PR on the way.
