### ISSUE TITLE
Multi-container Pods issue

### ISSUE THREAD

**Issue by amar-preet** [dgkanatsios/CKAD-exercises#145]
In Multi-container Pods section the second question is throwing an error 
```
apiVersion: v1
kind: Pod
metadata:
  labels:
    run: box
  name: box
spec:
  initContainers: #
  - args: #
    - /bin/sh #
    - -c #
    - wget -O /work-dir/index.html http://kubernetes.io #
    image: busybox #
    name: box #
    volumeMounts: #
    - name: vol #
      mountPath: /work-dir #
  containers:
  - image: nginx
    name: nginx
    ports:
    - containerPort: 80
    volumeMounts: #
    - name: vol #
      mountPath: /usr/share/nginx/html #
  volumes: #
  - name: vol #
    emptyDir: {} #
```

![image](https://user-images.githubusercontent.com/4614294/96520249-82a5ee80-1223-11eb-989c-de634e5913f7.png)
