### ISSUE TITLE
a.core_concepts.md minor issue 

### ISSUE THREAD

**Issue by leifliddy** [dgkanatsios/CKAD-exercises#156]
For the question ```Create the pod that was just described using YAML``` 
When you create the ```pod.yaml``` file with 
```kubectl run nginx --image=nginx --restart=Never --dry-run=client -n mynamespace -o yaml > pod.yaml``` 

The resulting yaml file will have the namespace listed in it ie 
```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: nginx
  name: nginx
  namespace: mynamespace
....
```
So, there's no need to specify the ```namespace``` when creating the pod with 
```kubectl create -f pod.yaml```
