### ISSUE TITLE
CDK new question 

### ISSUE THREAD

**Issue by gairik** [dgkanatsios/CKAD-exercises#233]
Create a similar 2 deployment and mark them as Blue and Green. Create a Service so that the load is balanced between Blue and Green at 75%-25% ratio. 
Does anyone know how can we do this kind if question?

**Comment by gairik** [comment]
`apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      color: green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        color: green
    spec:
     containers:
     - name: nginx
       image: nginx
       ports:
         - containerPort: 80
       volumeMounts:
         - mountPath: /usr/share/nginx/html/index.html
           name: nginx-conf
           subPath: index.html
     volumes:
        - name: nginx-conf
          configMap:
            name: config-green

---            
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-blue
  name: nginx-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      color: blue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        color: blue
    spec:
     containers:
     - name: nginx
       image: nginx
       ports:
         - containerPort: 80
       volumeMounts:
         - mountPath: /usr/share/nginx/html/index.html
           name: nginx-conf
           subPath: index.html
     volumes:
        - name: nginx-conf
          configMap:
            name: config`

**Comment by gairik** [comment]
```
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx
  name: nginx-green
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
      color: green
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        color: green
    spec:
     containers:
     - name: nginx
       image: nginx
       ports:
         - containerPort: 80
       volumeMounts:
         - mountPath: /usr/share/nginx/html/index.html
           name: nginx-conf
           subPath: index.html
     volumes:
        - name: nginx-conf
          configMap:
            name: config-green

---            
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: nginx-blue
  name: nginx-blue
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
      color: blue
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nginx
        color: blue
    spec:
     containers:
     - name: nginx
       image: nginx
       ports:
         - containerPort: 80
       volumeMounts:
         - mountPath: /usr/share/nginx/html/index.html
           name: nginx-conf
           subPath: index.html
     volumes:
        - name: nginx-conf
          configMap:
            name: config
```
