### ISSUE TITLE
Incorrect answer to solution?

### ISSUE THREAD

**Issue by ChrisCooney** [dgkanatsios/CKAD-exercises#5]
https://github.com/dgkanatsios/CKAD-exercises/blob/master/a.core_concepts.md

In the question "Create a busybox pod (using YAML) that runs the command "env". Run it and see the output", one would expect to see something like:

```
kubectl run busybox --image=busybox --restart=Never --dry-run -o yaml
```

Then add in the command slot to get a final yaml looking like this:

```
apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: null
  labels:
    run: busybox
  name: busybox
spec:
  containers:
  - image: busybox
    imagePullPolicy: IfNotPresent
    name: busybox
    command: ["env"]
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Never
status: {}
```

Apply and use `kubectl logs` to get the output.

Have I completely misunderstood here?
